version: '3.8'
services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/university
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=7d
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
